import { CardProps } from 'components'

export const cards: CardProps[] = [
  {
    title: 'Hooked',
    authors: ['Nir Eyal', 'Ryan Hoover'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2020,
  },
  {
    title: 'Crossing the Chasm',
    authors: ['Geoffrey A. Moore'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2016,
  },
  {
    title: 'Change By Design',
    authors: ['Tim Brown'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2020,
  },
  {
    title: 'Hooked',
    authors: ['Nir Eyal', 'Ryan Hoover'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2020,
  },
  {
    title: 'Crossing the Chasm',
    authors: ['Geoffrey A. Moore'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2016,
  },
  {
    title: 'Change By Design',
    authors: ['Tim Brown'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2020,
  },
  {
    title: 'Hooked',
    authors: ['Nir Eyal', 'Ryan Hoover'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2020,
  },
  {
    title: 'Crossing the Chasm',
    authors: ['Geoffrey A. Moore'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2016,
  },
  {
    title: 'Change By Design',
    authors: ['Tim Brown'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2020,
  },
  {
    title: 'Hooked',
    authors: ['Nir Eyal', 'Ryan Hoover'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2020,
  },
  {
    title: 'Crossing the Chasm',
    authors: ['Geoffrey A. Moore'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2016,
  },
  {
    title: 'Change By Design',
    authors: ['Tim Brown'],
    imageUrl: '/img/book-img-placeholder.png',
    pageCount: 150,
    publisher: 'Loyola',
    published: 2020,
  },
]
